apiVersion: v1
kind: Service
metadata:
  name: app-sample-svc
spec:
  type: NodePort
  ports:
  - name: app-sample-np
    protocol: TCP
    port: 8888
    nodePort: 30088
  selector:
    app: app-sample
